spring.application.name=vuejs

spring.datasource.url=jdbc:mysql://localhost:3306/vuejs
spring.datasource.username=root
spring.datasource.password=senai

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8088